apiVersion: v1
kind: Service
metadata:
  name: k8-model-api-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: k8-model-api
  type: LoadBalancer
  externalIPs:
    - 192.168.64.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-model-api
spec:
  selector:
    matchLabels:
      app: k8-model-api
  replicas: 2
  template:
    metadata:
      labels:
        app: k8-model-api
    spec:
      containers:
      - name: k8-model-api
        imagePullPolicy: Always
        image: gzmkobe/k8-model-api:latest
        command: ["python3",  "api.py"]
        ports:
        - containerPort: 5001