apiVersion: batch/v1
kind: Job
metadata:
  name: inference-job
spec:
  template:
    spec:
      containers:
      - name: inference-container
        imagePullPolicy: Always
        image: gzmkobe/k8-model:latest
        command: ["python3",  "inference.py"]
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
      restartPolicy: Never
  backoffLimit: 0